# Dockerfile
FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /app

# COPY requirements.txt .
# RUN pip install --upgrade pip && pip install -r requirements.txt

# 의존성 설치 (Djnago 기본본)
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# AI 기능 필요할 때만 다음 두 줄 사용
# COPY requirements-ai.txt .
# RUN pip install --no-cache-dir -r requirements-ai.txt

COPY . .

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]

# CMD ["gunicorn", "timtraveler.wsgi:application", "--bind", "0.0.0.0:8000"] # 배포 시 이 코드로 테스트
