# Generated by Django 5.2.4 on 2025-07-09 06:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('spots', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RouteSpot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order_number', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('route_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routespots', to='courses.route')),
                ('spot_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routespots', to='spots.spot')),
            ],
            options={
                'unique_together': {('route_id', 'order_number')},
            },
        ),
        migrations.CreateModel(
            name='UserRouteSpot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order_number', models.IntegerField()),
                ('unlock_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('route_spot_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userroutespots', to='courses.routespot')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userroutespots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user_id', 'route_spot_id')},
            },
        ),
    ]
