# Generated by Django 5.2.4 on 2025-08-28 11:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userroutespot',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='userroutespot',
            name='route_id',
            field=models.ForeignKey(default=14, on_delete=django.db.models.deletion.CASCADE, related_name='userroutespots', to='courses.route'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='userroutespot',
            unique_together={('user_id', 'route_spot_id', 'route_id')},
        ),
    ]
