# Generated by Django 5.2.4 on 2025-08-25 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='route',
            old_name='title',
            new_name='user_region_name',
        ),
        migrations.RenameField(
            model_name='routespot',
            old_name='order_number',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='userroutespot',
            old_name='order_number',
            new_name='order',
        ),
        migrations.RemoveField(
            model_name='route',
            name='description',
        ),
        migrations.AddField(
            model_name='route',
            name='is_mission_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='route',
            name='mission_spot_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='route',
            name='total_spots',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='routespot',
            unique_together={('route_id', 'order')},
        ),
    ]
