# Generated by Django 5.2.4 on 2025-09-01 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_userroutespot_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userroutespot',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
    ]
