# Generated by Django 5.2.4 on 2025-08-26 06:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('response', models.CharField(choices=[('walk', '걷기 좋은 길을 따라 즐기는 산책'), ('beach', '바다와 도시의 멋진 풍경/야경'), ('rest', '복잡한 곳을 피해 즐기는 휴식'), ('history', '역사와 문화가 담긴 특별한 체험'), ('fun', '지루할 틈 없는 다이나믹한 재미'), ('child', '아이와 함께'), ('couple', '연인과 함께'), ('friend', '친구와 함께'), ('family', '가족과 함께'), ('pet', '반려동물과 함께'), ('public', '대중교통으로'), ('car', '자차나 택시로'), ('popular', '사람들이 많이 찾는 유명한 곳 위주로'), ('facility', '시설이 깔끔하고 편리했으면 좋겠어요')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to=settings.AUTH_USER_MODEL)),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='questions.question')),
            ],
        ),
    ]
