# Generated by Django 5.2.4 on 2025-08-26 06:50

from django.db import migrations


def seed_questions(apps, schema_editor):
    Question = apps.get_model("questions", "Question")
    initial_data = [
        "어떤 여행을 원하시나요?",
        "누구와 함께 하나요?",
        "어떻게 이동하나요?",
        "그밖에 고려 사항이 있나요?",
    ]
    for text in initial_data:
        Question.objects.update_or_create(
            content=text,
            defaults={"type": "choice"},
        )

class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_questions, migrations.RunPython.noop),
    ]