# Generated by Django 5.2.4 on 2025-09-01 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image_url',
            field=models.TextField(blank=True),
        ),
    ]
