# Generated by Django 5.2.4 on 2025-08-13 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('photos', '0003_alter_photo_route_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='route_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_photos', to='courses.route'),
        ),
    ]
