# Generated by Django 5.2.4 on 2025-08-13 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_alter_photo_route_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image_url',
            field=models.ImageField(upload_to='photos/'),
        ),
    ]
