# Generated by Django 5.2.4 on 2025-08-28 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Spot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('era', models.CharField(blank=True, max_length=50)),
                ('content_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('content_type_id', models.CharField(blank=True, max_length=10)),
                ('category1', models.CharField(blank=True, max_length=10)),
                ('category2', models.CharField(blank=True, max_length=10)),
                ('category3', models.CharField(blank=True, max_length=10)),
                ('sigungu_code', models.CharField(blank=True, max_length=10)),
                ('use_time', models.TextField(blank=True)),
                ('first_image', models.URLField(blank=True)),
                ('first_image2', models.URLField(blank=True)),
                ('past_image_url', models.URLField(blank=True)),
                ('public_transport', models.BooleanField(default=False)),
                ('car_transport', models.BooleanField(default=False)),
                ('walking_activity', models.BooleanField(default=False)),
                ('with_children', models.BooleanField(default=False)),
                ('with_pets', models.BooleanField(default=False)),
                ('clean_facility', models.BooleanField(default=False)),
                ('night_view', models.BooleanField(default=False)),
                ('quiet_rest', models.BooleanField(default=False)),
                ('famous', models.BooleanField(default=False)),
                ('experience_info', models.BooleanField(default=False)),
                ('fun_sightseeing', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'spots',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SpotPhoto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='spot_photos/')),
                ('name', models.CharField(max_length=100)),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='spots.spot')),
            ],
        ),
    ]
