# Generated by Django 5.2.4 on 2025-07-09 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Spot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('era', models.CharField(max_length=50)),
            ],
        ),
    ]
