# Generated by Django 5.2.4 on 2025-08-01 14:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spot',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='spot',
            name='address',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='spot',
            name='car_transport',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='spot',
            name='category1',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='spot',
            name='category2',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='spot',
            name='category3',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='spot',
            name='clean_facility',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='spot',
            name='content_id',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='spot',
            name='content_type_id',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='spot',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spot',
            name='experience_info',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='spot',
            name='famous',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='spot',
            name='first_image',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='spot',
            name='first_image2',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='spot',
            name='fun_sightseeing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='spot',
            name='night_view',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='spot',
            name='past_image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='spot',
            name='public_transport',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='spot',
            name='quiet_rest',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='spot',
            name='sigungu_code',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='spot',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='spot',
            name='use_time',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='spot',
            name='walking_activity',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='spot',
            name='with_children',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='spot',
            name='with_pets',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='spot',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='spot',
            name='era',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='spot',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterModelTable(
            name='spot',
            table='spots',
        ),
        migrations.CreateModel(
            name='SpotPhoto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='spot_photos/')),
                ('name', models.CharField(max_length=100)),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='spots.spot')),
            ],
        ),
    ]
